@startuml

class Network{

}

class node{
  node_send_action(action,address)
  node_receive_state()

}

class IO{
  (...)
}

class Lights{
    bool inside/outside
    int floor
  lights_on(inside/outside, floor)
  lights_off(inside/outside, floor)
}

enum state{
  {IDLE,ARRIVED,RUNNING,EMERGENCY}
}

class Door{
  door_open()
  door_close()
}

class State{
  {IDLE,ARRIVED,RUNNING,EMERGENCY}

}

class Motor {
    bool d
    int v
    set_motor_dir(bool d)
    set_motor_voltage(int v)
    
}

Network <--> node

node <--> State

IO <--> Door

IO <--> Lights

State <-->Lights

State <--> Door

State <--> Motor

Motor <--> IO

@enduml
