@startuml

class Elevator  {
    queue active_queue
    elevator_send_action(master_ip,state)
    elevator_receive_state(master_ip)
    elevator_execute_order(queue destination)
    active_queue_remove(queue order)
    active_queue_add(queue order)
}
class Master{
    master_distribute_state(all_elevators)
    master_receive_message()
    master_IAmAlive(backup_ip)
    master_checkpoint()
}
class Network{
    network_send_message(ip, message)
}

class Backup{
    backup_boot_master()
    backup_send_state(all_elevators)
    backup_receive_state(master_ip)
}



enum queue {
    {{1,2,3,4,5,6,...,n},{UP,DOWN}}
}

Elevator  <-> Network: 1..n
Network <-> Master
Network <-> Backup





@enduml
