@startuml


HW --> ELEVATOR : Knapp er trykket
ELEVATOR --> NETWORK : Gjør klar melding om hva som har skjedd
NETWORK --> MASTER : Fortell at det har skjedd, oppdater hoveddokument
MASTER --> BACKUP : oppdatert tilstand
BACKUP --> MASTER : mottatt
MASTER --> NETWORK : fordel info på ALLE heiser
NETWORK --> ELEVATOR : distribuer tilstand
ELEVATOR --> HW : Skru på lys og begynn eventuell handling basert på kostnad
MASTER -->BACKUP : I am alive
ELEVATOR --> NETWORK : Fortell at jeg fortsatt er i operasjon
NETWORK --> MASTER : Fortell at heis i fortsatt er i operasjon
ELEVATOR --> NETWORK : Fortell at jeg fortsatt opererer
NETWORK --> MASTER : Fortell at heis fortsatt opererer
MASTER --> MASTER : Oppdater tilstand
MASTER --> NETWORK : Til alle noder oppdatert tilstand
NETWORK --> ELEVATOR : Oppdatert tilstand
NETWORK --> BACKUP : Oppdatert tilstand
HW --> ELEVATOR : En ordre er betjent
ELEVATOR --> NETWORK : Fortell at ordren er utført
NETWORK --> MASTER : Fortell at ordren er utført
MASTER --> BACKUP: oppdater tilstand
MASTER --> MASTER : Slett ordre
MASTER --> BACKUP : oppdater tilstand





@enduml
